### PR TITLE
Patch 2022 08 10

### PR DESCRIPTION
**Pull request by lukaszochmanski**
upgrade to the newer Gradle version > 7.0

### CODE REVIEW

**Comment by renatoathaydes** [comment]
Hi @lukaszochmanski . Feel free to take over this project if you find it useful.
I gave up because SDKMAN unpublishes older versions of SDKs all the time so it just broke CI a lot.
You could make it work, still, if you just tried to find the latest version of a SDK you can use for a certain config, but doing that would be a bit guesswork and would make CI unstable , which in my opinion is a dealbreaker.
So I am not maintaining this or using this anymore.

**Comment by lukaszochmanski** [comment]
Hi @renatoathaydes ,
This is great news. I couldn't publish a copy of your plugin, because they want me to maintain the existing plugin. This just solves my problem. Your plugin would be great if it worked with the newest version of Gradle. There is some incompatibility which I fixed. It looks good to me. 

Speaking of SDKMAN unpublished older versions, this is why I keep a backup of all versions locally, and I bring them to every project I work on :) If you would like to have some, I will gladly share it with you. I put all the java versions in private repositories for all developers and all CI pipelines will have this java version baked into the docker images. This is how I solve this. Besides, each Developer can pull the docker image directly and extract the JDK from there. Clearly, if I don’t have the latest/given JDK, you cannot run the pipeline, but this is ok. The CI/CD pipeline should work with the same JDK as it was developed with. If you don’t have it, it means that you cannot maintain the project with this version and you need to change the .sdkmanrc file. This is just my opinion. I loved your plugin and the idea behind it is great. If someone doesn’t like it, can simply disable it. This will be very easy to do, so it can only bring benefits to the project :)

I would love to maintain this project :)
How can I take over the repository?
Would you also be that kind and share access to the website that you created? It looks really good but add a few things here and there, for example new Gradle version, etc…

I am new to opensource, so I don’t know how this really works. Could you just give me the admin rights to the git repository so I can merge everything myself?


With regards,
Lukasz

**Comment by lukaszochmanski** [comment]
Hi Renato,
This is great news. I couldn't publish a copy of your plugin, because they want me to maintain the existing plugin. This just solves my problem. Your plugin would be great if it worked with the newest version of Gradle. There is some incompatibility which I fixed. It looks good to me. 

Speaking of SDKMAN unpublished older versions, this is why I keep a backup of all versions locally, and I bring them to every project I work on :) If you would like to have some, I will gladly share it with you. I put all the java versions in private repositories for all developers and all CI pipelines will have this java version baked into the docker images. This is how I solve this. Besides, each Developer can pull the docker image directly and extract the JDK from there. Clearly, if I don’t have the latest/given JDK, you cannot run the pipeline, but this is ok. The CI/CD pipeline should work with the same JDK as it was developed with. If you don’t have it, it means that you cannot maintain the project with this version and you need to change the .sdkmanrc file. This is just my opinion. I loved your plugin and the idea behind it is great. If someone doesn’t like it, can simply disable it. This will be very easy to do, so it can only bring benefits to the project :)

I would love to maintain this project :)
How can I take over the repository?
Would you also be that kind and share access to the website that you created? It looks really good but add a few things here and there, for example new Gradle version, etc…

I am new to opensource, so I don’t know how this really works. Could you just give me the admin rights to the git repository so I can merge everything myself?


With regards,
Lukasz

**Comment by renatoathaydes** [comment]
Hi Lukasz,

I can transfer the project to you but you need to delete your fork first.

By the way, while I don't mind you forked the project and changed my name everywhere with yours, this would be considered bad manners usually, as it looks as if you're stealing credit for the project.

If you wanted to just contribute to the project, you should make small changes from your fork and submit them as pull requests.

But as I don't have interest in this project anymore, I am willing to transfer everything to your name as long as you promise not to do anything malicious in the code, like add advertising, install unnecessary libraries and anything of that nature.

The website was created using a small static generator I wrote, [Magnanimous](https://renatoathaydes.github.io/magnanimous/). Should be easy for you to change the contents as it's all markdown with a custom template language (well documented on the website I linked) for generating dynamic content. And there's a few HTML and CSS files that get thrown together with the HTML generated from markdown, hopefully easy to "get" it.

**Comment by renatoathaydes** [comment]
With that said, It's not unusual for forks to take over from the original, unmaintained project...
It would actually prefer if you just kept developing on your own fork, actually.
I can archive this project and add a link in the README to your project... I think that would be more appropriate than transferring the repo.

The website is currently deployed on my personal GitHub account , so I cannot transfer the same URL to you, but you can easily publish the website on your own account or some new org to avoid this problem again in the future.

The Gradle plugin ID is also on my personal name (id "com.athaydes.sdkman"), so it just doesn't make sense for me to transfer that to you. Please change the Gradle ID and the Maven coordinates.

Does that work, you think?

**Comment by lukaszochmanski** [comment]
hi @renatoathaydes ,
I already went through all of this. I agree to the second idea. Here is how it went:

First I wanted to create a Pull Request. Then I realized, that there is no way that someone (you) will have time to review all those changes. I am going to make mistakes and there will be some bugFixes on a way. This would take forever and no one, especially the author wouldn't want to take suggestions from a stranger. Therefore, I decided to copy your code and put it in my own repo, so that I can work on this in isolation. The problem was the package name and the group ID which they should match. My group id should be the same as my gradle plugin respository account. As you said, it makes no sense to publish your name under my account. I had to change it. Now it looks, like your code was stolen. I changed everything locally and I pushed it into my git repository. Then I started to read the documentation, and that I will not be allowed to publish this plugin because it was based on some other plugin that is similar. The only way to make it work, is if I get written confirmation from the author of the plugin that the project is archived and not maintained any more. I went back and forth a few time, fork, clone, fork, clone. I gave up... and then you emailed me! Now there is hope :-)

I would honestly prefer option 2 as well. I will be much faster if I own the repo. Once I finish coding, you could add some note to README.md that this project was deprecated and there is a newer version under: https://github.com/lukaszochmanski/sdkman-gradle-plugin . I will do this as well on my side, so there is full transparency. I will add acknowledgments to the README.md that you were the original author of this project and that I had to change to group because this is how my account is called in Gradle Plugin Repository. I knew that this renaming looks bad. I was just experimenting with it. If I had left your name in the group, the chance that I would get permission to publish the plugin would be close to zero. I tried to remove your name so that they just let me do it. At the end I just got annoyed with it and I stopped. All your commits will be in Git history so this will acknowledge that you are the true author of the code. All I need from you is a short message that you 1. will not maintain this project. 2. you are going to archive it, 3. you allow me to use your code, and that we both decided not to work in one repository. We agreed that I will work on a separate fork, and my plugin should be published and used, with a new name, instead of the old one.

This is the right way of doing it. If you shoot me an email to github@ochmanski.de I will be able to take it from there and forward this email to the Gradle team for the review.

Thank you very much for your time and effort. I really appreciate.

Let me know what you think.

Lukasz

**Comment by lukaszochmanski** [comment]
and I also need the website. Where can I find the source code for it?

**Comment by renatoathaydes** [comment]
I will do that soon. The website is in the [website directory](https://github.com/renatoathaydes/sdkman-gradle-plugin/tree/master/website) :).

To build it:

```
cd website
magnanimous -style monokai
```

Configure GitHub Pages to deploy from the `website/target` directory (where the built website will be located after building).

EDIT: I forgot, there's a task to build the website with Gradle , so you can also do:

```
./gradlew website
```

And `./gradlew cleanWebsite` will clean `website/target`.

**Comment by renatoathaydes** [comment]
Oh, and once `website/target` exists, you can try it locally by using some webserver to serve that directory, it's just a static website.

**Pull request closed without merging**
